# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
      timezone: Asia/Tokyo
    commit-message:
      prefix: "change"
      include: "scope"
    labels:
      - "dependabot"
    target-branch: "dependabot/release"

  - package-ecosystem: "npm"
    directory: "/stop-human-wave-tactics-frontend"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
      timezone: Asia/Tokyo
    commit-message:
      prefix: "change"
      include: "scope"
    labels:
      - "dependabot"
    target-branch: "dependabot/release"

  - package-ecosystem: "npm"
    directory: "/stop-human-wave-tactics-backend"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
      timezone: Asia/Tokyo
    commit-message:
      prefix: "change"
      include: "scope"
    labels:
      - "dependabot"
    target-branch: "dependabot/release"
