version: "3"
services:
    proxy:
      image: nginx:stable
      ports:
        - "80:80"
      volumes:
        - ./nginx/conf.d/defalt.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - db
        - front
        - back
    db:
        image: postgres:13-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: stop_human_wave_tactics_db
        volumes:
            - dbData:/var/lib/postgresql/data
    back:
        build:
            context: ./stop-human-wave-tactics-backend
            dockerfile: Dockerfile
        ports:
            - "8000:1337"
        volumes:
            - backModules:/home/stop-human-wave-tactics-backend/node_modules
            - ./stop-human-wave-tactics-backend:/home/stop-human-wave-tactics-backend
        tty: true
        depends_on:
            - db
    front:
        build:
            context: ./stop-human-wave-tactics-frontend
            dockerfile: Dockerfile
        ports:
            - "8080:8000"
        volumes:
            - frontModules:/home/stop-human-wave-tactics-frontend/node_modules
            - ./stop-human-wave-tactics-frontend:/home/stop-human-wave-tactics-frontend
        depends_on:
            - back
            - db

volumes:
    dbData:
    frontModules:
    backModules:
