name: Production Deployment
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - name: Checkout and Build
        run: ./buildup.sh
